const ERC20Factory = [
    {
        "type":"function",
        "name":"createERC20Token",
        "inputs": [
            {
                "name":"_name",
                "type":"string",
                "internalType":"string"
            },
            {
                "name":"_ticker",
                "type":"string",
                "internalType":"string"
            },
            {
                "name":"_initialSupply",
                "type":"uint256",
                "internalType":"uint256"
            }
        ],
        "outputs":[],
        "stateMutability":"nonpayable"
    },
    {
        "type":"function",
        "name":"createERC20TokenWithURI",
        "inputs":
        [
            {
                "name":"_name",
                "type":"string",
                "internalType":"string"
            },
            {
                "name":"_ticker",
                "type":"string",
                "internalType":"string"
            },
            {
                "name":"_tokenURI",
                "type":"string",
                "internalType":"string"
            },
            {
                "name":"_initialSupply",
                "type":"uint256",
                "internalType":"uint256"
            }
        ],
        "outputs":[],
        "stateMutability":"nonpayable"
    },
    {
        "type":"event",
        "name":"NewTokenCreated",
        "inputs":[
            {
                "name":"tokenAddress",
                "type":"address",
                "indexed":true,
                "internalType":"address"
            },
            {
                "name":"tokenURI",
                "type":"string",
                "indexed":false,
                "internalType":"string"
            }
        ],
        "anonymous":false
    }
]

export default ERC20Factory;